### ISSUE TITLE
Website lists the wrong contributors

### ISSUE THREAD

**Issue by DreamyCodes** [AspectOSTeam/aspectosteam.github.io#3]
If you check the GitHub Pages website, it lists the contributors for Aspect inc, not Aspect OS. It's the Aspect _OS_ website though. Was it supposed to be this way?

**Comment by TheMowgliMan** [comment]
It was a copy and paste from the old website

**Comment by DreamyCodes** [comment]
> It was a copy and paste from the old website

Then the old website must have been wrong, too, because I have never been Co-CEO for AspectOS, but it lists me as such.

**Comment by AIGamesDeveloper** [comment]
> 

One of our website developers put that on the Glitch website. It is recommended to remove it kkidslogin

**Comment by TheMowgliMan** [comment]
Alrighty

**Comment by DreamyCodes** [comment]
ok, I'll close this issue. just remember to change it.
