### ISSUE TITLE
Set links colors to black, but heep the underline

### ISSUE THREAD

**Issue by ILOVETOMAKESTUFF** [AspectOSTeam/aspectosteam.github.io#7]
Since the background is constantly changing, the links are hard to see. Perhaps make the color black, blue on hover, but it will still have the underline? (So that people know that it is a link)

**Comment by AIGamesDeveloper** [comment]
I think that removing the gradient background would be better. We are trying to go with a more formal future and the gradient doesn't display that. I will let the contributors decide on whether or not to get rid of the gradient, and then I will see what I can do about this issue

**Comment by AIGamesDeveloper** [comment]
Hello! We have removed the gradient so there is no need to make the links black. I hope you understand! Thanks!
